#!/usr/bin/env php
<?php

use Dubpub\Publisher\Handlers\INIHandler;
use Dubpub\Publisher\Handlers\JSONHandler;
use Dubpub\Publisher\Handlers\PHPHandler;
use Dubpub\Publisher\Handlers\YAMLHandler;

use Symfony\Component\Yaml\Dumper;
use Symfony\Component\Yaml\Parser;

$success = false;

foreach (['/vendor/autoload.php', '/../autoload.php', '/../../autoload.php'] as $path) {
    if (file_exists($loaderFilename = __DIR__ . $path)) {
        include $loaderFilename;
        $success = true;
    }
}

if (!$success) {
    die('Unable to locate autoloader\n');
}

$scanner = new \Dubpub\Publisher\PublisherScanner();

$scanner->registerTypeHandler('php', PHPHandler::class);
$scanner->registerTypeHandler('json', JSONHandler::class);
$scanner->registerTypeHandler('ini', INIHandler::class);
$scanner->registerTypeHandler('yaml', $yaml = new YAMLHandler(new Parser(), new Dumper()));
$scanner->registerTypeHandler('yml', $yaml);

$application = new \Symfony\Component\Console\Application();
$application->setName('Dubpub: publisher');
$application->setVersion('1.0');
$application->add(new \Dubpub\Publisher\Commands\PublishCommand('publish', $scanner));
$application->add(new \Dubpub\Publisher\Commands\InitCommand('init', $scanner));
$application->run();